ERROR    2021-06-10 16:36:12.022 request id: app - __main__:read_subdivision_org - division by zero
Traceback (most recent call last):

  File "/usr/lib64/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f114bc7f488>
    └ <Thread(ThreadPoolExecutor-0_1, started daemon 139711855191808)>
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f114bc7f268>
    └ <Thread(ThreadPoolExecutor-0_1, started daemon 139711855191808)>
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_1, started daemon 139711855191808)>
    │    │        │    └ (<weakref at 0x7f1142555d18; to 'ThreadPoolExecutor' at 0x7f1142556a90>, <queue.Queue object at 0x7f1142556ac8>)
    │    │        └ <Thread(ThreadPoolExecutor-0_1, started daemon 139711855191808)>
    │    └ <function _worker at 0x7f1147d92598>
    └ <Thread(ThreadPoolExecutor-0_1, started daemon 139711855191808)>
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 69, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f1147d926a8>
    └ <concurrent.futures.thread._WorkItem object at 0x7f1142556be0>
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f1142556be0>
             │    │   │    └ (functools.partial(<function read_subdivision_org at 0x7f114449b730>, db=<sqlalchemy.orm.session.Session object at 0x7f114255...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f1142556be0>
             │    └ <bound method Context.run of <contextvars.Context object at 0x7f1142556940>>
             └ <concurrent.futures.thread._WorkItem object at 0x7f1142556be0>
  File "/home/api/signer-api/env/lib64/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
           │         │       └ {}
           │         └ ()
           └ functools.partial(<function read_subdivision_org at 0x7f114449b730>, db=<sqlalchemy.orm.session.Session object at 0x7f1142556...

> File "/home/api/signer-api/apiapp.py", line 56, in read_subdivision_org
    1/0

ZeroDivisionError: division by zero
